Fix for OSX building on Mojave x86
Support building on older mojave for the x86 binary -- do workarounds
for that specific case.

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -76,11 +76,16 @@ have_brew=`which brew`
 have_macports=`which port`
 if [ -n "$have_brew" ]; then
     info "Ensuring build prerequisites are installed via brew"
-    brew info openssl@1.1 > /dev/null 2>&1 && OPENSSL="openssl@1.1" || OPENSSL=openssl
-    brew info autoconf-archive > /dev/null 2>&1 && AUTOCONF_ARCHIVE="autoconf-archive" || AUTOCONF_ARCHIVE=""
-    brew info libiconv > /dev/null 2>&1 && LIBICONV="libiconv" || LIBICONV=""
-    for a in autoconf $AUTOCONF_ARCHIVE automake coreutils gettext $LIBICONV libtool $OPENSSL pkgconf readline sqlite3 \
-             xz zlib swig ; do
+    if [ $(uname -m) == "x86_64" ] && (( $(uname -r | cut -f 1 -d .) <= 18 )); then
+        # Legacy
+	pkgs="autoconf automake coreutils gettext libtool openssl@1.1 readline sqlite3 xz zlib swig"
+    else
+        brew info openssl@1.1 > /dev/null 2>&1 && OPENSSL="openssl@1.1" || OPENSSL=openssl
+        brew info autoconf-archive > /dev/null 2>&1 && AUTOCONF_ARCHIVE="autoconf-archive" || AUTOCONF_ARCHIVE=""
+        brew info libiconv > /dev/null 2>&1 && LIBICONV="libiconv" || LIBICONV=""
+        pkgs="autoconf $AUTOCONF_ARCHIVE automake coreutils gettext $LIBICONV libtool $OPENSSL pkgconf readline sqlite3 xz zlib swig"
+    fi
+    for a in $pkgs; do
         brew list $a > /dev/null 2>&1
         if [ "$?" != "0" ]; then
             info "Installing $a"
@@ -234,14 +239,28 @@ contrib/make_zlib && contrib/make_libevent && contrib/make_openssl && contrib/ma
 
 info "Installing requirements..."
 python3 -m pip install -r ./contrib/deterministic-build/requirements.txt --user || fail "Could not install requirements"
-#python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
-# Note that on macos the deterministic requirements-binaries now fails, fall back to simple requirements. We are not deterministic anyway on this platform so it's fine.
-python3 -m pip install -r ./contrib/requirements/requirements-binaries-osx-sonoma.txt --user || fail "Could not install binary requirements"
+if [ $(uname -m) == "x86_64" ] && (( $(uname -r | cut -f 1 -d .) <= 18 )); then
+    # Building on mojave, with older brew, etc, this works.
+    info "Older macOS: Using pinned requirements-binaries"
+    python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
+else
+    # Note that on newer macos the deterministic requirements-binaries now fails, fall back to simple requirements.
+    # We are not deterministic anyway on this platform so it's fine.
+    info "Newer macOS: Using non-pinned requirements-binaries"
+    python3 -m pip install -r ./contrib/requirements/requirements-binaries-osx-sonoma.txt --user || fail "Could not install binary requirements"
+fi
 
 info "Installing hardware wallet requirements..."
-#python3 -m pip install -r ./contrib/deterministic-build/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
-# Note that on macos the deterministic requirements-hw now fails, fall back to simple requirements. We are not deterministic anyway on this platform so it's fine.
-python3 -m pip install -r ./contrib/requirements/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
+if [ $(uname -m) == "x86_64" ] && (( $(uname -r | cut -f 1 -d .) <= 18 )); then
+    # Building on mojave, with older brew, etc, this works.
+    info "Older macOS: Using pinned requirements-hw"
+    python3 -m pip install -r ./contrib/deterministic-build/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
+else
+    # Note that on newer macos the deterministic requirements-hw now fails, fall back to simple requirements.
+    # We are not deterministic anyway on this platform so it's fine.
+    info "Newer macOS: Using non-pinned requirements-hw"
+    python3 -m pip install -r ./contrib/requirements/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
+fi
 
 info "Building $PACKAGE..."
 python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
